### ISSUE TITLE
Webcamoid update

### ISSUE THREAD

**Issue by opusforlife2** [riedel/chocolatey-packages#12]
Hi. Apparently, it got an update last year and none of us noticed. XD

Could you please update the package to 9.0.0?

**Comment by riedel** [comment]
I tried it however, the installer changed and then I was stupidly blocked updating the package after unsuccessful submission. It is a pain because I need manual moderation from the chocolatey admins...

 I was waiting for something like 9.0.1 to be released. Actually I think the package is building, I might try it again.

**Comment by riedel** [comment]
hopefully works now https://community.chocolatey.org/packages/webcamoid/9.0.0 . still needs review
